# Generated by Django 4.2.4 on 2023-08-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                (
                    "notes_created",
                    models.IntegerField(
                        default=0, verbose_name="amount_of_notes_posted"
                    ),
                ),
            ],
        ),
    ]
