# Generated by Django 4.2.4 on 2023-08-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_notes_category_status_alter_notes_node_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="category_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soc", "Социальные науки"),
                    ("gum", "Гуманитарные науки"),
                    ("est", "Естественные и точные науки"),
                    ("med", "Медицинские науки"),
                    ("tech", "Техника и технологии"),
                    ("selhoz", "Сельскохозяйственные науки"),
                ],
                default="no status selected",
                help_text="text_type",
                max_length=255,
            ),
        ),
    ]
