# Generated by Django 4.2.4 on 2023-08-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_notes_category_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToValidateNotes',
            fields=[
                ('notes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.notes')),
            ],
            bases=('main.notes',),
        ),
    ]
