# Generated by Django 4.2.4 on 2023-08-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tovalidatenotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='state_status',
            field=models.CharField(blank=True, choices=[('approve', 'Проверенно'), ('disapprove', 'Не проверенно')], default='no status selected', help_text='text_type', max_length=255),
        ),
        migrations.DeleteModel(
            name='ToValidateNotes',
        ),
    ]
