# Generated by Django 4.2.4 on 2023-09-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_notes_state_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='norm_status',
            field=models.CharField(blank=True, choices=[('norm', 'нормальный'), ('test', 'тестовый')], default='test', help_text='text_type', max_length=255),
        ),
    ]
